#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model RelayCoordination.Tests.TestLatchPowerToRealFault
 Dymola Version 2019 (64-bit), 2018-04-11 translated this at Tue Apr 30 19:38:51 2019

   */

#include <matrixop.h>
/* DSblock C-code: */

#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="RelayCoordination.Tests.TestLatchPowerToRealFault";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "/home/manuelnvro/.dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
