#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model OCRAIOSPSAT.Components.RelayCalibration
 Dymola Version 2019 FD01 (64-bit), 2018-10-10 translated this at Tue Aug 27 11:23:26 2019

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    1
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    52
#define NP_    67
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 664770277
#define NHash2_ 877901097
#define NHash3_ 0
#define NI_    0
#define NRelF_ 2
#define NRel_  8
#define NTim_  3
#define NSamp_ 0
#define NCons_ 0
#define NA_    97
#define SizePre_ 3
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 2
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="OCRAIOSPSAT.Components.RelayCalibration";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "/home/marcelo/.dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,48) = 3;
DYNX(W_,29) = 0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,6) = DYNX(DP_,34);
DYNX(W_,15) = DYNX(DP_,61);
DYNX(W_,16) = DYNX(DP_,62);
DYNX(W_,26) = DYNX(W_,16);
DYNX(W_,17) = DYNX(W_,26);
DYNX(W_,28) = DYNX(DP_,34);
DYNX(W_,19) = DYNX(W_,28);
DYNX(W_,24) = DYNX(W_,15);
DYNX(W_,23) = DYNX(W_,24);
DYNX(W_,25) = DYNX(DP_,35);
DYNX(W_,27) = DYNX(DP_,51);
DYNX(W_,40) =  NOT DYNX(DP_,47);
DYNX(W_,43) =  NOT DYNX(DP_,49);
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(X_,0) = DYNX(DP_,56);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,41);
DYNX(Aux_,1) = DYNX(W_,44);
InitialSection
InitialSection2
DYNX(X_,0) = DYNX(DP_,56);
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,40);
DYNX(Aux_,1) = DYNX(W_,43);
InitialSection
InitialSection2
DYNX(W_,41) = DYNX(Aux_,0);
DYNX(W_,44) = DYNX(Aux_,1);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,42) = PRE(DYNX(W_,44), 1);
DYNX(W_,4) =  NOT (DYNX(W_,42) OR DYNX(DP_,50));
DYNX(W_,5) = IF DYNX(W_,4) THEN DYNX(DP_,23) ELSE DYNX(DP_,24);
DYNX(W_,46) = GreaterEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,54),"recordReferenceRelay.extractingTimeOfFault.greaterEqualThreshold.threshold",
   0);
DYNX(W_,47) = IF DYNX(W_,46) THEN DYNX(DP_,52) ELSE DYNX(DP_,53);
DYNX(F_,0) = DYNX(DP_,55)*DYNX(W_,47);

AcceptedSection1
DYNX(W_,49) = IF GreaterEqualTime(DYNX(DP_,57), 0) THEN  NOT DYNX(DP_,58) ELSE 
  DYNX(DP_,58);
DYNX(W_,50) = IF DYNX(W_,49) THEN DYNX(DP_,59) ELSE DYNX(DP_,60);
DYNX(W_,51) = DYNX(W_,50)*DYNX(DP_,66);
DYNX(W_,45) = DYNX(DP_,63)*DYNX(W_,51)+DYNX(DP_,64)*DYNX(DP_,65);
DYNX(W_,3) = Greater(DYNX(W_,45),"recordReferenceRelay.u", DYNX(W_,6),
  "recordReferenceRelay.const.k", 1);
DYNX(W_,44) =  NOT (DYNX(W_,3) OR DYNX(W_,4));

AcceptedSection2
DYNX(W_,0) = DYNX(W_,5)*DYNX(X_,0);
DYNX(W_,11) = GreaterEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,32),"recordReferenceRelay.timer.greaterEqualThreshold.threshold", 2);
DYNX(W_,7) = DYNX(DP_,25)+(IF LessTime(DYNX(DP_,26), 1) THEN 0 ELSE DYNTime-
  DYNX(DP_,26));
DYNX(W_,10) = DYNX(W_,7)*DYNX(DP_,29);
DYNX(W_,8) = IF DYNX(W_,11) THEN DYNX(DP_,33) ELSE DYNX(W_,10);
DYNX(W_,9) = DYNX(DP_,30)+(IF LessTime(DYNX(DP_,31), 2) THEN 0 ELSE DYNTime-
  DYNX(DP_,31));
DYNX(W_,1) = DYNX(DP_,27)*DYNX(W_,8)+DYNX(DP_,28)*DYNX(W_,9);
DYNX(W_,2) = DYNX(DP_,21)*DYNX(W_,0)+DYNX(DP_,22)*DYNX(W_,1);
DYNX(W_,38) = LessEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,45),"recordReferenceRelay.calculatingOperationTime.lessEqualThreshold1.threshold",
   3);
DYNX(W_,37) = GreaterEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,44),"recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold1.threshold",
   4);
DYNX(W_,36) =  NOT (DYNX(W_,38) AND DYNX(W_,37));
DYNX(W_,31) = IF DYNX(W_,36) THEN DYNX(W_,17) ELSE DYNX(DP_,46);
DYNX(W_,35) = LessEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,42),"recordReferenceRelay.calculatingOperationTime.lessEqualThreshold.threshold",
   5);
DYNX(W_,34) = GreaterEqual(DYNX(W_,5),"recordReferenceRelay.booleanToReal1.y", 
  DYNX(DP_,41),"recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold.threshold",
   6);
DYNX(W_,33) =  NOT (DYNX(W_,35) AND DYNX(W_,34));
DYNX(W_,18) = divmacro(DYNX(W_,45),"recordReferenceRelay.u",DYNX(W_,19),
  "recordReferenceRelay.calculatingOperationTime.pickcupcurrent.k");
DYNX(W_,20) = powmacro(DYNX(W_,18),"recordReferenceRelay.calculatingOperationTime.division1.y",
  DYNX(W_,23),"recordReferenceRelay.calculatingOperationTime.const.k");
DYNX(W_,21) = DYNX(DP_,37)*DYNX(W_,20)+DYNX(DP_,38)*DYNX(DP_,36);
DYNX(W_,30) = divmacro(DYNX(DP_,40),"recordReferenceRelay.calculatingOperationTime.const4.k",
  DYNX(W_,21),"recordReferenceRelay.calculatingOperationTime.add.y");
DYNX(W_,32) = IF DYNX(W_,33) THEN DYNX(W_,30) ELSE DYNX(DP_,43);
DYNX(W_,22) = DYNX(W_,31)*DYNX(W_,32);
DYNX(W_,13) = DYNX(W_,22)*DYNX(DP_,39);
DYNX(W_,14) = Greater(DYNX(W_,2),"recordReferenceRelay.add.y", DYNX(W_,13),
  "recordReferenceRelay.greater2.u2", 7);
DYNX(W_,39) = PRE(DYNX(W_,41), 2);
DYNX(W_,12) =  NOT (DYNX(W_,39) OR DYNX(DP_,48));
DYNX(W_,41) =  NOT (DYNX(W_,14) OR DYNX(W_,12));

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [MVA]", 0, 750, 0.0,0.0,0.0,0,560)
DeclareParameter("SysData.fn", "System Frequency [Hz]", 1, 50, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.InfiniteBusV_0", "", 2, 1.06, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.InfiniteBusangle_0", "", 3, 0.0, 0.0,0.0,0.0,\
0,560)
DeclareParameter("PowerFlow.voltage.BreakerenableTrigger", "[:#(type=Boolean)]",\
 4, false, 0.0,0.0,0.0,0,562)
DeclareParameter("PowerFlow.voltage.TransformerB3B4m", "", 5, 9999, 0.0,0.0,0.0,\
0,560)
DeclareParameter("PowerFlow.voltage.GeneratorV_0", "", 6, 1.04, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.Generatorangle_0", "", 7, 8.8, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.MotorV_0", "", 8, 1.0078, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.Motorangle_0", "", 9, 4.9, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.PQLoadV_0", "", 10, 1.0675, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.voltage.PQLoadangle_0", "", 11, 4.7, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.InfiniteBusP_0", "", 12, -350, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.InfiniteBusQ_0", "", 13, -16, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.GeneratorP_0", "", 14, 450, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.GeneratorQ_0", "", 15, 99, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.PQLoadP_0", "", 16, 100, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.PQLoadQ_0", "", 17, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.MotorP_0", "", 18, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.MotorQ_0", "", 19, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("PowerFlow.power.ShuntCapacitorQnom", "", 20, 117, 0.0,0.0,0.0,\
0,560)
DeclareVariable("recordReferenceRelay.add.u1", "Connector of Real input signal 1",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("recordReferenceRelay.add.u2", "Connector of Real input signal 2",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("recordReferenceRelay.add.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("recordReferenceRelay.add.k1", "Gain of upper input", 21, -1, \
0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.add.k2", "Gain of lower input", 22, 1, \
0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.greater1.u1", "Connector of first Boolean input signal",\
 "recordReferenceRelay.u", 1, 5, 45, 0)
DeclareAlias2("recordReferenceRelay.greater1.u2", "Connector of second Boolean input signal",\
 "recordReferenceRelay.const.k", 1, 5, 6, 0)
DeclareVariable("recordReferenceRelay.greater1.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareVariable("recordReferenceRelay.booleanToReal1.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareParameter("recordReferenceRelay.booleanToReal1.realTrue", \
"Output signal for true Boolean input", 23, 1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.booleanToReal1.realFalse", \
"Output signal for false Boolean input", 24, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.booleanToReal1.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("recordReferenceRelay.const.k", "Constant output value", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("recordReferenceRelay.const.y", "Connector of Real output signal",\
 "recordReferenceRelay.const.k", 1, 5, 6, 0)
DeclareParameter("recordReferenceRelay.timer.clock.offset", "Offset of output signal [s]",\
 25, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.timer.clock.startTime", "Output = offset for time < startTime [s]",\
 26, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.timer.clock.y", "Connector of Real output signal [s]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("recordReferenceRelay.timer.add.u1", "Connector of Real input signal 1",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("recordReferenceRelay.timer.add.u2", "Connector of Real input signal 2 [s]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("recordReferenceRelay.timer.add.y", "Connector of Real output signal",\
 "recordReferenceRelay.add.u2", 1, 5, 1, 0)
DeclareParameter("recordReferenceRelay.timer.add.k1", "Gain of upper input", 27,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.timer.add.k2", "Gain of lower input", 28,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.timer.const.k", "Constant output value", 29,\
 -1, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.timer.const.y", "Connector of Real output signal",\
 "recordReferenceRelay.timer.const.k", 1, 7, 29, 0)
DeclareAlias2("recordReferenceRelay.timer.product.u1", "Connector of Real input signal 1 [s]",\
 "recordReferenceRelay.timer.clock.y", 1, 5, 7, 0)
DeclareAlias2("recordReferenceRelay.timer.product.u2", "Connector of Real input signal 2",\
 "recordReferenceRelay.timer.const.k", 1, 7, 29, 0)
DeclareVariable("recordReferenceRelay.timer.product.y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("recordReferenceRelay.timer.clock1.offset", "Offset of output signal [s]",\
 30, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.timer.clock1.startTime", "Output = offset for time < startTime [s]",\
 31, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.timer.clock1.y", "Connector of Real output signal [s]",\
 "recordReferenceRelay.timer.add.u2", 1, 5, 9, 0)
DeclareAlias2("recordReferenceRelay.timer.u", "", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareAlias2("recordReferenceRelay.timer.y", "", "recordReferenceRelay.add.u2", 1,\
 5, 1, 0)
DeclareParameter("recordReferenceRelay.timer.greaterEqualThreshold.threshold", \
"Comparison with respect to threshold", 32, 0.9, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.timer.greaterEqualThreshold.u", \
"Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareVariable("recordReferenceRelay.timer.greaterEqualThreshold.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.timer.switch1.u1", "Connector of first Real input signal",\
 "recordReferenceRelay.timer.const1.k", 1, 7, 33, 0)
DeclareAlias2("recordReferenceRelay.timer.switch1.u2", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.timer.greaterEqualThreshold.y", 1, 5, 11, 65)
DeclareAlias2("recordReferenceRelay.timer.switch1.u3", "Connector of second Real input signal",\
 "recordReferenceRelay.timer.product.y", 1, 5, 10, 0)
DeclareAlias2("recordReferenceRelay.timer.switch1.y", "Connector of Real output signal",\
 "recordReferenceRelay.timer.add.u1", 1, 5, 8, 0)
DeclareParameter("recordReferenceRelay.timer.const1.k", "Constant output value",\
 33, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.timer.const1.y", "Connector of Real output signal",\
 "recordReferenceRelay.timer.const1.k", 1, 7, 33, 0)
DeclareParameter("recordReferenceRelay.Is", "Pick Up Current Value", 34, 400, \
0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.TripSingal", "[:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.greater2.u1", "Connector of first Boolean input signal",\
 "recordReferenceRelay.add.y", 1, 5, 2, 0)
DeclareVariable("recordReferenceRelay.greater2.u2", "Connector of second Boolean input signal",\
 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("recordReferenceRelay.greater2.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareVariable("recordReferenceRelay.alpha", "Alpha Constant Value", 0.0, \
0.0,0.0,0.0,0,513)
DeclareParameter("recordReferenceRelay.TMS", "TMS Constant Value", 35, 0.5, \
0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.C", "C Constant Value", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.CurrentInput", "", \
"recordReferenceRelay.u", 1, 5, 45, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.OperationTime", "",\
 "recordReferenceRelay.greater2.u2", 1, 5, 13, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.Const.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.Const.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.Const.k", 1,\
 5, 17, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.division1.u1", \
"Connector of Real input signal 1", "recordReferenceRelay.u", 1, 5, 45, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.division1.u2", \
"Connector of Real input signal 2", "recordReferenceRelay.calculatingOperationTime.pickcupcurrent.k", 1,\
 5, 19, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.division1.y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.pickcupcurrent.k",\
 "Constant output value", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.pickcupcurrent.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.pickcupcurrent.k", 1,\
 5, 19, 0)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.const2.k", \
"Constant output value", 36, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.const2.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.const2.k", 1,\
 7, 36, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.add.u1", \
"Connector of Real input signal 1", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.add.u2", \
"Connector of Real input signal 2", "recordReferenceRelay.calculatingOperationTime.const2.k", 1,\
 7, 36, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.add.y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,640)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.add.k1", \
"Gain of upper input", 37, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.add.k2", \
"Gain of lower input", 38, -1, 0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.product.u1", \
"Connector of Real input signal 1", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.product.u2", \
"Connector of Real input signal 2", "recordReferenceRelay.calculatingOperationTime.TimeMultiplierSetting.k", 1,\
 7, 39, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.product.y", \
"Connector of Real output signal", "recordReferenceRelay.greater2.u2", 1, 5, 13,\
 0)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.TimeMultiplierSetting.k",\
 "Constant output value", 39, 0.5, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.TimeMultiplierSetting.y",\
 "Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.TimeMultiplierSetting.k", 1,\
 7, 39, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.toThePower1.u", "",\
 "recordReferenceRelay.calculatingOperationTime.division1.y", 1, 5, 18, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.toThePower1.y", "",\
 "recordReferenceRelay.calculatingOperationTime.add.u1", 1, 5, 20, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.toThePower1.alpha",\
 "", "recordReferenceRelay.calculatingOperationTime.const.k", 1, 5, 23, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.const.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.const.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.const.k", 1,\
 5, 23, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.alpha", \
"Constant output value", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.TMS", \
"Constant output value", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.C", \
"Constant output value", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.eps", \
"Constant output value", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.Is", \
"Constant output value", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.amp", \
"[:#(type=Integer)]", 0, 0.0,0.0,0.0,0,517)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.division.u1", \
"Connector of Real input signal 1", "recordReferenceRelay.calculatingOperationTime.const4.k", 1,\
 7, 40, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.division.u2", \
"Connector of Real input signal 2", "recordReferenceRelay.calculatingOperationTime.add.y", 1,\
 5, 21, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.division.y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,640)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.const4.k", \
"Constant output value", 40, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.const4.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.const4.k", 1,\
 7, 40, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.product1.u1", \
"Connector of Real input signal 1", 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.product1.u2", \
"Connector of Real input signal 2", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.product1.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.product.u1", 1,\
 5, 22, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.Control", "", \
"recordReferenceRelay.booleanToReal1.y", 1, 5, 5, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch1.u1", \
"Connector of first Real input signal", "recordReferenceRelay.calculatingOperationTime.division.y", 1,\
 5, 30, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.switch1.u2", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch1.u3", \
"Connector of second Real input signal", "recordReferenceRelay.calculatingOperationTime.const1.k", 1,\
 7, 43, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch1.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.product1.u2", 1,\
 5, 32, 0)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold.threshold",\
 "Comparison with respect to threshold", 41, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold.u",\
 "Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold.y",\
 "Connector of Boolean output signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold.threshold",\
 "Comparison with respect to threshold", 42, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold.u",\
 "Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold.y",\
 "Connector of Boolean output signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand.u1", \
"Connector of first Boolean input signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.lessEqualThreshold.y", 1,\
 5, 35, 65)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand.u2", \
"Connector of second Boolean input signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold.y", 1,\
 5, 34, 65)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.switch1.u2", 1,\
 5, 33, 65)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.const1.k", \
"Constant output value", 43, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.const1.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.const1.k", 1,\
 7, 43, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch2.u1", \
"Connector of first Real input signal", "recordReferenceRelay.calculatingOperationTime.Const.k", 1,\
 5, 17, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.switch2.u2", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch2.u3", \
"Connector of second Real input signal", "recordReferenceRelay.calculatingOperationTime.const3.k", 1,\
 7, 46, 0)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.switch2.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.product1.u1", 1,\
 5, 31, 0)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold1.threshold",\
 "Comparison with respect to threshold", 44, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold1.u",\
 "Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold1.y",\
 "Connector of Boolean output signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold1.threshold",\
 "Comparison with respect to threshold", 45, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold1.u",\
 "Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareVariable("recordReferenceRelay.calculatingOperationTime.lessEqualThreshold1.y",\
 "Connector of Boolean output signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand1.u1", \
"Connector of first Boolean input signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.lessEqualThreshold1.y", 1,\
 5, 38, 65)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand1.u2", \
"Connector of second Boolean input signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.greaterEqualThreshold1.y", 1,\
 5, 37, 65)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.nand1.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "recordReferenceRelay.calculatingOperationTime.switch2.u2", 1,\
 5, 36, 65)
DeclareParameter("recordReferenceRelay.calculatingOperationTime.const3.k", \
"Constant output value", 46, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.calculatingOperationTime.const3.y", \
"Connector of Real output signal", "recordReferenceRelay.calculatingOperationTime.const3.k", 1,\
 7, 46, 0)
DeclareParameter("recordReferenceRelay.rSFlipFlop.Qini", "Start value of Q at initial time [:#(type=Boolean)]",\
 47, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.Q", "[:#(type=Boolean)]", \
"recordReferenceRelay.TripSingal", 1, 5, 12, 65)
DeclareVariable("recordReferenceRelay.rSFlipFlop.QI", "[:#(type=Boolean)]", \
false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor.u1", "Connector of first Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.greater2.y", 1, 5, 14, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor.u2", "Connector of second Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.TripSingal", 1, 5, 12, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop.pre.u", 1, 5, 41, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor1.u1", "Connector of first Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop.QI", 1, 5, 39, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor1.u2", "Connector of second Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanConstant.k", 1, 7, 48, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.nor1.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.TripSingal", 1, 5, 12, 65)
DeclareVariable("recordReferenceRelay.rSFlipFlop.pre.pre_u_start", \
"Start value of pre(u) at initial time [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("recordReferenceRelay.rSFlipFlop.pre.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.pre.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop.QI", 1, 5, 39, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.S", "[:#(type=Boolean)]", \
"recordReferenceRelay.greater2.y", 1, 5, 14, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop.R", "[:#(type=Boolean)]", \
"recordReferenceRelay.booleanConstant.k", 1, 7, 48, 65)
DeclareParameter("recordReferenceRelay.booleanConstant.k", "Constant output value [:#(type=Boolean)]",\
 48, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("recordReferenceRelay.booleanConstant.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanConstant.k", 1, 7, 48, 65)
DeclareParameter("recordReferenceRelay.rSFlipFlop1.Qini", "Start value of Q at initial time [:#(type=Boolean)]",\
 49, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.Q", "[:#(type=Boolean)]", \
"recordReferenceRelay.booleanToReal1.u", 1, 5, 4, 65)
DeclareVariable("recordReferenceRelay.rSFlipFlop1.QI", "[:#(type=Boolean)]", \
false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor.u1", "Connector of first Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.greater1.y", 1, 5, 3, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor.u2", "Connector of second Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanToReal1.u", 1, 5, 4, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop1.pre.u", 1, 5, 44, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor1.u1", "Connector of first Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop1.QI", 1, 5, 42, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor1.u2", "Connector of second Boolean input signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanConstant1.k", 1, 7, 50, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.nor1.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanToReal1.u", 1, 5, 4, 65)
DeclareVariable("recordReferenceRelay.rSFlipFlop1.pre.pre_u_start", \
"Start value of pre(u) at initial time [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("recordReferenceRelay.rSFlipFlop1.pre.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.pre.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.rSFlipFlop1.QI", 1, 5, 42, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.S", "[:#(type=Boolean)]", \
"recordReferenceRelay.greater1.y", 1, 5, 3, 65)
DeclareAlias2("recordReferenceRelay.rSFlipFlop1.R", "[:#(type=Boolean)]", \
"recordReferenceRelay.booleanConstant1.k", 1, 7, 50, 65)
DeclareParameter("recordReferenceRelay.booleanConstant1.k", "Constant output value [:#(type=Boolean)]",\
 50, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("recordReferenceRelay.booleanConstant1.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 "recordReferenceRelay.booleanConstant1.k", 1, 7, 50, 65)
DeclareVariable("recordReferenceRelay.u", "", 0.0, 0.0,0.0,0.0,0,640)
DeclareParameter("recordReferenceRelay.eps", "Constant output value", 51, 0.41, \
0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.y", "", \
"recordReferenceRelay.add.u1", 1, 5, 0, 0)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.u", "", \
"recordReferenceRelay.booleanToReal1.y", 1, 5, 5, 0)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.switch1.u1", \
"Connector of first Real input signal", "recordReferenceRelay.extractingTimeOfFault.const.k", 1,\
 7, 52, 0)
DeclareVariable("recordReferenceRelay.extractingTimeOfFault.switch1.u2", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,642)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.switch1.u3", \
"Connector of second Real input signal", "recordReferenceRelay.extractingTimeOfFault.const1.k", 1,\
 7, 53, 0)
DeclareVariable("recordReferenceRelay.extractingTimeOfFault.switch1.y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.product.u1", \
"Connector of Real input signal 1", "recordReferenceRelay.booleanToReal1.y", 1, 5,\
 5, 0)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.product.u2", \
"Connector of Real input signal 2", "recordReferenceRelay.extractingTimeOfFault.integrator.y", 1,\
 1, 0, 0)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.product.y", \
"Connector of Real output signal", "recordReferenceRelay.add.u1", 1, 5, 0, 0)
DeclareParameter("recordReferenceRelay.extractingTimeOfFault.const.k", \
"Constant output value", 52, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.const.y", \
"Connector of Real output signal", "recordReferenceRelay.extractingTimeOfFault.const.k", 1,\
 7, 52, 0)
DeclareParameter("recordReferenceRelay.extractingTimeOfFault.const1.k", \
"Constant output value", 53, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.const1.y", \
"Connector of Real output signal", "recordReferenceRelay.extractingTimeOfFault.const1.k", 1,\
 7, 53, 0)
DeclareParameter("recordReferenceRelay.extractingTimeOfFault.greaterEqualThreshold.threshold",\
 "Comparison with respect to threshold", 54, 0.9, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.greaterEqualThreshold.u",\
 "Connector of Boolean input signal", "recordReferenceRelay.booleanToReal1.y", 1,\
 5, 5, 0)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.greaterEqualThreshold.y",\
 "Connector of Boolean output signal [:#(type=Boolean)]", "recordReferenceRelay.extractingTimeOfFault.switch1.u2", 1,\
 5, 46, 65)
DeclareParameter("recordReferenceRelay.extractingTimeOfFault.integrator.k", \
"Integrator gain [1]", 55, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("recordReferenceRelay.extractingTimeOfFault.integrator.initType",\
 "Type of initialization (1: no init, 2: steady state, 3,4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 3, 1.0,4.0,0.0,0,517)
DeclareParameter("recordReferenceRelay.extractingTimeOfFault.integrator.y_start",\
 "Initial or guess value of output (= state)", 56, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("recordReferenceRelay.extractingTimeOfFault.integrator.u", \
"Connector of Real input signal", "recordReferenceRelay.extractingTimeOfFault.switch1.y", 1,\
 5, 47, 0)
DeclareState("recordReferenceRelay.extractingTimeOfFault.integrator.y", \
"Connector of Real output signal", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("recordReferenceRelay.extractingTimeOfFault.integrator.der(y)",\
 "der(Connector of Real output signal)", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("booleanStep.startTime", "Time instant of step start [s]", 57, 7,\
 0.0,0.0,0.0,0,560)
DeclareParameter("booleanStep.startValue", "Output before startTime [:#(type=Boolean)]",\
 58, false, 0.0,0.0,0.0,0,562)
DeclareVariable("booleanStep.y", "Connector of Boolean output signal [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,642)
DeclareAlias2("booleanToReal.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "booleanStep.y", 1, 5, 49, 65)
DeclareParameter("booleanToReal.realTrue", "Output signal for true Boolean input",\
 59, 1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("booleanToReal.realFalse", "Output signal for false Boolean input",\
 60, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("booleanToReal.y", "Connector of Real output signal", 0.0, \
0.0,0.0,0.0,0,640)
DeclareParameter("RelayData.alpha.alpha", "", 61, 0.02, 0.0,0.0,0.0,0,560)
DeclareParameter("RelayData.c.C", "", 62, 0.14, 0.0,0.0,0.0,0,560)
DeclareVariable("add.u1", "Connector of Real input signal 1", 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("add.u2", "Connector of Real input signal 2", "const.k", 1, 7, 65,\
 0)
DeclareAlias2("add.y", "Connector of Real output signal", "recordReferenceRelay.u", 1,\
 5, 45, 0)
DeclareParameter("add.k1", "Gain of upper input", 63, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("add.k2", "Gain of lower input", 64, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("const.k", "Constant output value", 65, 0.3, 0.0,0.0,0.0,0,560)
DeclareAlias2("const.y", "Connector of Real output signal", "const.k", 1, 7, 65,\
 0)
DeclareAlias2("product.u1", "Connector of Real input signal 1", "booleanToReal.y", 1,\
 5, 50, 0)
DeclareAlias2("product.u2", "Connector of Real input signal 2", "const1.k", 1, 7,\
 66, 0)
DeclareAlias2("product.y", "Connector of Real output signal", "add.u1", 1, 5, 51,\
 0)
DeclareParameter("const1.k", "Constant output value", 66, 10133333, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("const1.y", "Connector of Real output signal", "const1.k", 1, 7, 66,\
 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preWD(DYNX(W_,46),"recordReferenceRelay.extractingTimeOfFault.switch1.u2", false,
   0);
pre(DYNX(W_,41),"recordReferenceRelay.rSFlipFlop.pre.u", false, 2);
pre(DYNX(W_,44),"recordReferenceRelay.rSFlipFlop1.pre.u", false, 1);
EndPreBlock
EndDataBlock
